package protocol

// port from OpenIPMI
// Chassis Network Function
const (
	IPMI_CMD_GET_CHASSIS_CAPABILITIES =	0x00
	IPMI_CMD_GET_CHASSIS_STATUS =		0x01
	IPMI_CMD_CHASSIS_CONTROL =		0x02
	IPMI_CMD_CHASSIS_RESET =		0x03
	IPMI_CMD_CHASSIS_IDENTIFY =		0x04
	IPMI_CMD_SET_CHASSIS_CAPABILITIES =	0x05
	IPMI_CMD_SET_POWER_RESTORE_POLICY =	0x06
	IPMI_CMD_GET_SYSTEM_RESTART_CAUSE =	0x07
	IPMI_CMD_SET_SYSTEM_BOOT_OPTIONS =	0x08
	IPMI_CMD_GET_SYSTEM_BOOT_OPTIONS =	0x09
	IPMI_CMD_GET_POH_COUNTER =		0x0f
)